apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql8
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql8
    spec:
      containers:
      - image: mysql:5.7.21
        name: mysql
        imagePullPolicy: Never
        env:
        - name: MYSQL_DATABASE
          value: my_db
        - name: MYSQL_PASSWORD
          value: kubertest
        - name: MYSQL_ROOT_PASSWORD
          value: kubertest
        ports:
        - containerPort: 3306
          name: mysql8
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
